# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron:  '0 18 * * 4'
   
  workflow_dispatch:  
  
jobs:
  start:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      UPSTREAM_REPOSITORY: ${{ secrets.UPR }}
      TARGET_REPOSITORY: ${{ secrets.TGR }}
      TARGET_BRANCH: main
      UPSTREAM_BRANCH: main
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${UPSTREAM_REPOSITORY}.git"
          upstream_dir=${UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          #git rm -r -f --cached .github
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #git commit -m "rm workflows"
          git push --force --follow-tags --tags "${target_repo}" "${UPSTREAM_BRANCH}:${TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"        
  sync:
    runs-on: ubuntu-latest
    needs: start
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      UPSTREAM_REPOSITORY: ${{ secrets.UPR1 }}
      TARGET_REPOSITORY: ${{ secrets.TGR1 }}
      TARGET_BRANCH: main
      UPSTREAM_BRANCH: main
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${UPSTREAM_REPOSITORY}.git"
          upstream_dir=${UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          DATE=`date +%Y%m%d%H%M%S`
          echo "current git push time: $DATE"
          sed -i "1i$DATE" time.txt
          git add time.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "update"
          git push --force --follow-tags --tags "${target_repo}" "${UPSTREAM_BRANCH}:${TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"          
